name:                api-maker
version:             0.1.0.2
github:              "schnecki/api-maker"
license:             BSD3
author:              "Manuel Schneckenreither"
maintainer:          "manuel.schneckenreither@uibk.ac.at"
copyright:           "2019 Manuel Schneckenreither"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Package to make APIs
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/schnecki/api-maker#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- req
- http-client
- http-client-tls
- http-types
- text
- transformers-base
- transformers
- containers
- monad-control
- mtl
- lens
- http-api-data
- easy-logger


library:
  source-dirs: src
  ghc-options:
    -Wall
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wredundant-constraints
    -fwarn-tabs
    -fno-warn-name-shadowing
    -O2
    -funbox-strict-fields
  when:
    - condition: impl(ghc < 8.0)
      ghc-options:       -fno-warn-incomplete-patterns
      cpp-options:       -DType=*

    - condition: impl(ghc >= 8.6)
      default-extensions: NoStarIsType

tests:
  api-maker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api-maker
